version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: b2b-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: b2b-collab
    volumes:
      - mongo-data:/data/db

  api:
    build: ./server
    container_name: b2b-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  mongo-data: